#!/usr/bin/env python3
"""Validate the dry-run Google Meet Calendar PoC script."""

from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path


SCRIPT = Path(__file__).with_name("google_meet_calendar_poc.py")


BASE_ARGS = [
    sys.executable,
    str(SCRIPT),
    "--calendar-id",
    "primary",
    "--summary",
    "PatronPro Onboarding - Demo Auto Shop",
    "--description",
    "Generated by PatronPro onboarding automation dry-run.",
    "--start",
    "2026-06-15T10:00:00-06:00",
    "--end",
    "2026-06-15T11:00:00-06:00",
    "--timezone",
    "America/Mexico_City",
    "--attendee-email",
    "client@example.com",
    "--attendee-name",
    "Demo Client",
    "--ghl-appointment-id",
    "ghl_appt_demo_123",
    "--patronpro-onboarding-id",
    "onboarding_demo_123",
    "--dry-run",
]


def run_case(args: list[str], env: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    return subprocess.run(args, text=True, capture_output=True, env=env, check=False)


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def assert_positive_contract() -> None:
    result = run_case(BASE_ARGS)
    require(result.returncode == 0, result.stderr)
    payload = json.loads(result.stdout)

    require(payload["mode"] == "dry-run", "mode must be dry-run")
    require(payload["piiRedacted"] is True, "PII must be redacted by default")
    require(payload["request"]["method"] == "POST", "method mismatch")
    require(payload["request"]["url"] == "https://www.googleapis.com/calendar/v3/calendars/primary/events", "url mismatch")
    require(payload["request"]["query"]["conferenceDataVersion"] == 1, "conferenceDataVersion must be integer 1")
    require(payload["request"]["query"]["sendUpdates"] == "none", "sendUpdates default mismatch")

    event = payload["event"]
    require(event["attendees"][0]["email"] == "***@***", "attendee email must be redacted")
    require(event["start"]["dateTime"].endswith("-06:00"), "start must be offset-aware")
    require(event["start"]["timeZone"] == "America/Mexico_City", "start timezone mismatch")
    require(event["end"]["timeZone"] == "America/Mexico_City", "end timezone mismatch")
    require(event["reminders"]["useDefault"] is False, "reminder overrides require useDefault false")
    require(event["extendedProperties"]["private"]["ghlAppointmentId"] == "ghl_appt_demo_123", "missing GHL correlation")
    require(event["conferenceData"]["createRequest"]["conferenceSolutionKey"]["type"] == "hangoutsMeet", "Meet type mismatch")
    request_id = event["conferenceData"]["createRequest"]["requestId"]
    require(request_id.startswith("dryrun_ppweb_0ka_4_"), "dry-run requestId prefix mismatch")
    require(request_id not in {"fresh-unique-request-id", "REPLACE_BEFORE_LIVE_USE"}, "placeholder requestId leaked")


def assert_failure(extra_args: list[str], expected: str, env: dict[str, str] | None = None) -> None:
    result = run_case(BASE_ARGS + extra_args, env=env)
    require(result.returncode != 0, f"expected failure for {extra_args}")
    require(expected in result.stderr, f"expected {expected!r} in stderr, got {result.stderr!r}")


def assert_negative_contracts() -> None:
    assert_failure(["--start", "2026-06-15T10:00:00"], "start must include a numeric UTC offset")
    assert_failure(["--timezone", "Not/AZone"], "timezone must be a valid IANA timezone")
    assert_failure(["--send-updates", "all"], "--allow-send-updates is required")
    assert_failure(["--execute"], "--confirm-live is required")
    assert_failure(["--execute", "--confirm-live"], "--credentials-path is required")
    assert_failure(["--conference-data-version", "0"], "conferenceDataVersion must be exactly integer 1")

    env = os.environ.copy()
    env["PATRONPRO_GOOGLE_MEET_LIVE_TOKEN"] = "local-test-confirmation"
    with tempfile.TemporaryDirectory() as temp_dir:
        credentials = Path(temp_dir) / "credentials.json"
        token = Path(temp_dir) / "token.json"
        credentials.write_text("{}", encoding="utf-8")
        token.write_text("{}", encoding="utf-8")
        assert_failure(
            [
                "--execute",
                "--confirm-live",
                "--credentials-path",
                str(credentials),
                "--token-path",
                str(token),
                "--request-id",
                "fresh-unique-request-id",
            ],
            "requestId placeholder is not allowed",
            env=env,
        )


def main() -> int:
    assert_positive_contract()
    assert_negative_contracts()
    print("google_meet_calendar_poc validation passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
