export interface LabHtmlInput {
  businessName: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  domain?: string;
  tagline: string;
  services: string[];
  primaryColor: string;
  secondaryColor: string;
}

export interface LabHtmlImages {
  hero?: string | null;
  about?: string | null;
  contact?: string | null;
}

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

export function buildLabWebsiteHtml(p: LabHtmlInput, images: LabHtmlImages): string {
  const services = (p.services.length ? p.services : ["Reemplazo de techo", "Reparacion de fugas", "Inspeccion de techo"])
    .slice(0, 6);
  const primary = p.primaryColor || "#471f23";
  const accent = p.secondaryColor || "#f69309";
  const heroImage = images.hero || "";
  const aboutImage = images.about || "";
  const contactImage = images.contact || heroImage || aboutImage || "";
  const description = p.tagline || "Website lab generated by PatronPro";
  const schema = [
    {
      "@context": "https://schema.org",
      "@type": ["LocalBusiness", "ProfessionalService"],
      name: "{{custom_values.company_name}}",
      url: "https://{{custom_values.dominio_web}}/",
      image: "{{custom_values.website_social_image}}",
      logo: "{{custom_values.logo_cuadrado}}",
      telephone: "{{custom_values.company_phone}}",
      email: "{{custom_values.automation_sender_email}}",
      address: "{{custom_values.company_address}}",
      areaServed: { "@type": "City", name: p.city },
      description,
      makesOffer: services.slice(0, 4).map((service) => ({
        "@type": "Offer",
        itemOffered: { "@type": "Service", name: service },
      })),
    },
    {
      "@context": "https://schema.org",
      "@type": "ItemList",
      name: "Servicios",
      itemListElement: services.map((service, index) => ({
        "@type": "ListItem",
        position: index + 1,
        name: service,
        url: "https://{{custom_values.dominio_web}}/#servicios",
      })),
    },
    {
      "@context": "https://schema.org",
      "@type": "SiteNavigationElement",
      name: ["Servicios", "Nosotros", "Contacto"],
      url: [
        "https://{{custom_values.dominio_web}}/#servicios",
        "https://{{custom_values.dominio_web}}/#nosotros",
        "https://{{custom_values.dominio_web}}/#contacto",
      ],
    },
  ];

  return `<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(p.businessName)} | Lab Website</title>
  <meta name="description" content="${escapeHtml(description)}">
  <link rel="canonical" href="https://{{custom_values.dominio_web}}/">
  <meta name="robots" content="index,follow,max-image-preview:large">
  <meta property="og:type" content="website">
  <meta property="og:locale" content="es_US">
  <meta property="og:site_name" content="{{custom_values.company_name}}">
  <meta property="og:title" content="${escapeHtml(p.businessName)} | ${escapeHtml(p.city)}">
  <meta property="og:description" content="${escapeHtml(description)}">
  <meta property="og:url" content="https://{{custom_values.dominio_web}}/">
  <meta property="og:image" content="{{custom_values.website_social_image}}">
  <meta property="og:image:secure_url" content="{{custom_values.website_social_image}}">
  <meta property="og:image:type" content="image/jpeg">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta property="og:image:alt" content="{{custom_values.company_name}}">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="${escapeHtml(p.businessName)} | ${escapeHtml(p.city)}">
  <meta name="twitter:description" content="${escapeHtml(description)}">
  <meta name="twitter:image" content="{{custom_values.website_social_image}}">
  <script type="application/ld+json">${JSON.stringify(schema)}</script>
  <style>
    :root{--primary:${primary};--accent:${accent};--text:#1f2937;--muted:#64748b;--bg:#f8fafc}
    *{box-sizing:border-box}body{margin:0;font-family:Inter,Arial,sans-serif;color:var(--text);background:var(--bg);line-height:1.55}
    header{background:var(--primary);color:#fff;padding:18px 24px;display:flex;justify-content:space-between;align-items:center;gap:16px}
    header strong{font-size:20px}a{color:inherit}.btn{display:inline-flex;align-items:center;justify-content:center;padding:12px 18px;background:var(--accent);color:#111;font-weight:800;text-decoration:none}
    .hero{position:relative;min-height:520px;display:grid;place-items:center;color:#fff;background:var(--primary);overflow:hidden}
    .hero img,.image-band img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;opacity:.42}
    .hero-content{position:relative;max-width:960px;padding:56px 24px;text-align:center}.hero h1{font-size:clamp(34px,6vw,58px);line-height:1;margin:0 0 18px}.hero p{font-size:20px;margin:0 auto 28px;max-width:720px}
    section{padding:64px 24px}.wrap{max-width:1120px;margin:0 auto}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:18px}.card{background:#fff;border-left:5px solid var(--accent);padding:22px;box-shadow:0 10px 30px rgba(15,23,42,.08)}
    .image-band{position:relative;min-height:340px;background:var(--primary);color:#fff;overflow:hidden}.image-band .wrap{position:relative;padding:78px 24px}.image-band p{max-width:720px}
    footer{background:#111827;color:#fff;padding:32px 24px}
  </style>
</head>
<body>
  <header><strong>${escapeHtml(p.businessName)}</strong><a class="btn" href="tel:{{custom_values.company_phone}}">Llamar ahora</a></header>
  <main>
    <section class="hero">${heroImage ? `<img src="${escapeHtml(heroImage)}" alt="">` : ""}<div class="hero-content"><h1>${escapeHtml(p.tagline || "Tu techo listo para durar")}</h1><p>Lab page generated from the PatronPro panel. Use this page to test refresh, regenerate, and optimized asset replacement.</p><a class="btn" href="#contacto">Pedir cotizacion</a></div></section>
    <section id="servicios"><div class="wrap"><h2>Servicios</h2><div class="grid">${services.map((service) => `<article class="card" id="servicio-${escapeHtml(service.toLowerCase().replaceAll(" ", "-"))}"><h3>${escapeHtml(service)}</h3><p>Servicio profesional con comunicacion clara, precio justo y trabajo garantizado.</p></article>`).join("")}</div></div></section>
    <section id="nosotros" class="image-band">${aboutImage ? `<img src="${escapeHtml(aboutImage)}" alt="">` : ""}<div class="wrap"><h2>Nosotros</h2><p>Equipo local con enfoque practico: revisar, explicar y resolver sin rodeos. Este bloque conserva la copia cuando actualizas referencias de imagen.</p></div></section>
    <section id="contacto" class="image-band">${contactImage ? `<img src="${escapeHtml(contactImage)}" alt="">` : ""}<div class="wrap"><h2>Contacto</h2><p>${escapeHtml(p.address)}, ${escapeHtml(p.city)}, ${escapeHtml(p.state)} ${escapeHtml(p.zip)}</p><a class="btn" href="tel:{{custom_values.company_phone}}">Llamar {{custom_values.company_phone}}</a></div></section>
  </main>
  <footer><div class="wrap">${escapeHtml(p.businessName)} - Lab website</div></footer>
</body>
</html>`;
}
