export interface LabHtmlInput {
  businessName: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  tagline: string;
  services: string[];
  primaryColor: string;
  secondaryColor: string;
}

export interface LabHtmlImages {
  hero?: string | null;
  about?: string | null;
  contact?: string | null;
}

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

export function buildLabWebsiteHtml(p: LabHtmlInput, images: LabHtmlImages): string {
  const services = (p.services.length ? p.services : ["Reemplazo de techo", "Reparacion de fugas", "Inspeccion de techo"])
    .slice(0, 6);
  const primary = p.primaryColor || "#471f23";
  const accent = p.secondaryColor || "#f69309";
  const heroImage = images.hero || "";
  const aboutImage = images.about || "";
  const contactImage = images.contact || heroImage || aboutImage || "";

  return `<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(p.businessName)} | Lab Website</title>
  <meta name="description" content="${escapeHtml(p.tagline || "Website lab generated by PatronPro")}">
  <style>
    :root{--primary:${primary};--accent:${accent};--text:#1f2937;--muted:#64748b;--bg:#f8fafc}
    *{box-sizing:border-box}body{margin:0;font-family:Inter,Arial,sans-serif;color:var(--text);background:var(--bg);line-height:1.55}
    header{background:var(--primary);color:#fff;padding:18px 24px;display:flex;justify-content:space-between;align-items:center;gap:16px}
    header strong{font-size:20px}a{color:inherit}.btn{display:inline-flex;align-items:center;justify-content:center;padding:12px 18px;background:var(--accent);color:#111;font-weight:800;text-decoration:none}
    .hero{position:relative;min-height:520px;display:grid;place-items:center;color:#fff;background:var(--primary);overflow:hidden}
    .hero img,.image-band img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;opacity:.42}
    .hero-content{position:relative;max-width:960px;padding:56px 24px;text-align:center}.hero h1{font-size:clamp(34px,6vw,58px);line-height:1;margin:0 0 18px}.hero p{font-size:20px;margin:0 auto 28px;max-width:720px}
    section{padding:64px 24px}.wrap{max-width:1120px;margin:0 auto}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:18px}.card{background:#fff;border-left:5px solid var(--accent);padding:22px;box-shadow:0 10px 30px rgba(15,23,42,.08)}
    .image-band{position:relative;min-height:340px;background:var(--primary);color:#fff;overflow:hidden}.image-band .wrap{position:relative;padding:78px 24px}.image-band p{max-width:720px}
    footer{background:#111827;color:#fff;padding:32px 24px}
  </style>
</head>
<body>
  <header><strong>${escapeHtml(p.businessName)}</strong><a class="btn" href="tel:{{custom_values.company_phone}}">Llamar ahora</a></header>
  <main>
    <section class="hero">${heroImage ? `<img src="${escapeHtml(heroImage)}" alt="">` : ""}<div class="hero-content"><h1>${escapeHtml(p.tagline || "Tu techo listo para durar")}</h1><p>Lab page generated from the PatronPro panel. Use this page to test refresh, regenerate, and optimized asset replacement.</p><a class="btn" href="#contacto">Pedir cotizacion</a></div></section>
    <section><div class="wrap"><h2>Servicios</h2><div class="grid">${services.map((service) => `<article class="card"><h3>${escapeHtml(service)}</h3><p>Servicio profesional con comunicacion clara, precio justo y trabajo garantizado.</p></article>`).join("")}</div></div></section>
    <section class="image-band">${aboutImage ? `<img src="${escapeHtml(aboutImage)}" alt="">` : ""}<div class="wrap"><h2>Nosotros</h2><p>Equipo local con enfoque practico: revisar, explicar y resolver sin rodeos. Este bloque conserva la copia cuando actualizas referencias de imagen.</p></div></section>
    <section id="contacto" class="image-band">${contactImage ? `<img src="${escapeHtml(contactImage)}" alt="">` : ""}<div class="wrap"><h2>Contacto</h2><p>${escapeHtml(p.address)}, ${escapeHtml(p.city)}, ${escapeHtml(p.state)} ${escapeHtml(p.zip)}</p><a class="btn" href="tel:{{custom_values.company_phone}}">Llamar {{custom_values.company_phone}}</a></div></section>
  </main>
  <footer><div class="wrap">${escapeHtml(p.businessName)} - Lab website</div></footer>
</body>
</html>`;
}
